[font]
size = 10 

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
opacity=0.95

[terminal]
osc52 = "CopyPaste"


# colors
[colors.primary]
background = "#0d1117"
foreground = "#c9d1d9"

[colors.cursor]
text = "#0d1117"
cursor = "#c9d1d9"

[colors.normal]
black = "#484f58"
red = "#ff7b72"
green = "#58a6ff"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[colors.bright]
black = "#6e7681"
red = "#ffa198"
green = "#79c0ff"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[[keyboard.bindings]]
key = "Semicolon"
mods = "Control"
chars = "\u000C"  # This is Ctrl+L (form feed) which clears the screen

