return {}
-- return {
-- 	{
-- 		"nvim-telescope/telescope.nvim",
-- 		branch = "0.1.x",
-- 		dependencies = { "nvim-lua/plenary.nvim", "folke/todo-comments.nvim" },
-- 		config = function()
-- 			local builtin = require("telescope.builtin")
-- 			vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find all files" })
-- 			vim.keymap.set("n", "<C-p>", builtin.git_files, { desc = "Find added git files" }) -- note: this is dublicated with fg. But I want to keep it this way. You can remove
-- 			vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "Find added git files" })
-- 			vim.keymap.set("n", "<leader>fs", builtin.live_grep, { desc = "Search in all files" })
-- 			vim.api.nvim_set_keymap(
-- 				"n",
-- 				"<leader>p",
-- 				":Telescope neovim-project discover<CR>",
-- 				{ noremap = true, silent = true }
-- 			)
-- 		end,
-- 	},
-- 	{
-- 		"nvim-telescope/telescope-ui-select.nvim",
-- 		config = function()
-- 			local actions = require("telescope.actions")
-- 			require("telescope").setup({
-- 				defaults = {
-- 					path_display = { "smart" },
-- 					mappings = {
-- 						i = {
-- 							["<C-k>"] = actions.move_selection_previous, -- move to prev result
-- 							["<C-j>"] = actions.move_selection_next, -- move to next result
-- 							["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
-- 						},
-- 					},
-- 				},
-- 				extensions = {
-- 					["ui-select"] = {
-- 						require("telescope.themes").get_dropdown({}),
-- 					},
-- 				},
-- 			})
-- 			require("telescope").load_extension("ui-select")
-- 		end,
-- 	},
-- }
